name: Update gist with new hitokoto

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: fcb1d163cd79766d2388cfd016023194
      CATEGORY: a
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Update gist
        run: go run .
